# permissions to do viewer wordpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordpress-viewer-role
rules:
- apiGroups:
  - wordpress.dployx.io
  resources:
  - wordpresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wordpress.dployx.io
  resources:
  - wordpresses/status
  verbs:
  - get
