apiVersion: wordpress.dployx.io/v1
kind: Wordpress
metadata:
  name: wordpress-sample
spec:
  replicas: 3
  domains:
    - example.com
  dbhost: db.example.com
  dbname: exampledb
  dbuser: exampledbuser
  dbpassword: exampledbpass
